### ISSUE TITLE
Ability to use Mongo instead of SQL

### ISSUE THREAD

**Issue by gdelfresno** [rayokota/generator-angular-flask#7]
Hi

I'm managing the possibility to add support for MongoDB to your generator. It's my first time developing a yeoman generator, but I think it would we easy to do it. My idea is to add an option when running the generator thats allows the user to choose between SQLAlchemy and MongoDB. 

Do you think it's worth it? Or should I just fork your repo and replace everything related to SQLAlchemy with MongoDB?

I'd like to know your opinion because it's very likely that I end up trying to do it. 

Thanks in advance.

**Comment by rayokota** [comment]
Hi, I'm trying to keep the generators fairly similar to the other ones at https://github.com/rayokota/MicroFrameworkRosettaStone, so probably best for you to fork it.  Thanks for your inquiry.
